[package]
name = "day-03"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part1"
path = "src/bin/part1.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
